#!/usr/bin/env python

import sys

from artemis_sysmon.sysmon import Sysmon
from rqt_gui.main import Main

plugin = 'artemis_sysmon'
main = Main(filename=plugin)
sys.exit(main.main(sys.argv, standalone=plugin))
